[phases.setup]
nixPkgs = ["sqlite", "gcc", "g++", "gnumake", "python3", "nodejs"]

[phases.build]
cmds = ["npm install --prefix backend", "cd backend && npm rebuild sqlite3 --build-from-source"]

[variables]
LD_LIBRARY_PATH = ""
